create table UNION1(
  id INT,
  stock INT
);

INSERT INTO UNION1 VALUES (1,25);
INSERT INTO UNION1 VALUES (1,25);
INSERT INTO UNION1 VALUES(7,95);
INSERT INTO UNION1 VALUES(6,65);
INSERT INTO UNION1 VALUES (2,45);
INSERT INTO UNION1 VALUES (5,85);

create table UNION2(
  id INT NOT NULL,
  stock INT
);


INSERT INTO UNION2 VALUES (3,65);
INSERT INTO UNION2 VALUES (2,45);
INSERT INTO UNION2 VALUES (2,45);
INSERT INTO UNION2 VALUES (5,85);

-- select DISTINCT * from UNION1
-- ←DISTINCTを使うと重複しているものを除くことが可能

update UNION1 set stock = 88 where id = 6;

select * from UNION1
UNION ALL
select * from UNION2

